version: '3.7'

services:
  db:
    image: postgres:15
    container_name: grass_postgres
    restart: always
    networks:
      - djangonetwork
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build:
      context: .
    restart: unless-stopped
    command: >
      sh -c "sleep 5 && \
             python manage.py migrate && \
             python manage.py collectstatic && \
             gunicorn --bind 0.0.0.0:8000 app.wsgi
    env_file: .env
    volumes:
      - .:/home/ivan/grass
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork


networks:
    djangonetwork:
        driver: bridge

volumes:
  pg_data:
  static_data: