version: '3.7'

services:
  db:
    image: postgres:15
    container_name: grass_postgres
    restart: always
    networks:
      - djangonetwork
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build:
      context: .
    command: >
      sh -c "sleep 5 && \
             python manage.py migrate && \
             python manage.py collectstatic && \
             python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/grass
      - static_data:./staticfiles
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  nginx:
    image: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx-conf.d:/etc/nginx/conf.d


networks:
    djangonetwork:
        driver: bridge

volumes:
  pg_data:
  static_data: