version: '3.7'

services:
  db:
    image: postgres:13.3
    container_name: grass_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic &&
             python manage.py runserver"
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./grass/:/usr/src/grass/
  nginx:


