version: "3.9"

services:
  database:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresqlcls
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-prod

  web:
    build:
      context: .
    ports:
      - 8000:9999
    volumes:
      - /app:/grass/
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - database
      - redis
    env_file:
      - .env-prod

  redis:
    image: redis:alpine
    container_name: redis

#  nginx:
#    build: ./nginx
#    restart: unless-stopped
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#      - media_volume:/home/app/web/media
#    depends_on:
#      - web



volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
