version: '3.7'

services:
  db:
    image: postgres:15
    container_name: grass_postgres
    restart: always
    networks:
      - djangonetwork
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
  web:
    build:
      context: .
    restart: unless-stopped
    command: >
      sh -c "sleep 1 && \
             python manage.py migrate && \
             python manage.py collectstatic --no-input && \
             gunicorn --bind 0.0.0.0:8000 grass.wsgi:application"
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - media:/media
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
    djangonetwork:
        driver: bridge

volumes:
  pgdata:
  media: